### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by gagan-bansal** [ConnorChristie/Set-System-Time#2]
I am getting following Error
```bash
> var DateTimeControl = require('set-system-clock');
> DateTimeControl.setDateTime(new Date('8/1/2017 13:14:12'));
TypeError: DateTimeControl.setDateTime is not a function
```
My node version
```bash
$ node -v
v8.12.0
```

**Comment by adamlarsonlee** [comment]
Same thing here.

node v12.13.0

This is working for me:

```javascript
const { DateTimeControl } = require('set-system-clock');
const clock = new DateTimeControl();
```

**Comment by Coffee-Boyy** [comment]
@gagan-bansal The method `setDateTime` on `DateTimeControl` is not static so you have to do what was just said above and create a new instance of the date time control before calling the method.

**Comment by adamlarsonlee** [comment]
You may want to change the readme since the code example doesn't reflect that.

**Comment by gagan-bansal** [comment]
> Same thing here.
> 
> node v12.13.0
> 
> This is working for me:
> 
> ```js
> const { DateTimeControl } = require('set-system-clock');
> const clock = new DateTimeControl();
> ```

Yes working for me, but how to set time further?
Thanks

**Comment by adamlarsonlee** [comment]
```javascript
const { DateTimeControl } = require('set-system-clock');
const clock = new DateTimeControl();
clock.setDateTime(new Date());
```

Here you want to replace new Date() with the date you want to set the system time with. This is my [source file](https://github.com/activated-research-company/solvere/blob/master/api/api/src/clock/clock.js) if you're curious.

**Comment by gagan-bansal** [comment]
Thanks, I'll check the source.

I think I misunderstood the purpose of this repo.
Please see if below code is fine. My expected output is '2020-04-**18**T02:39:.....Z'
But output is '2020-04-**19**T02:46:12.782Z'
```js
const { DateTimeControl } = require('set-system-clock');
const clock = new DateTimeControl();
clock.setDateTime(new Date('2020-04-18T02:39:36.312Z'));
console.log(new Date())
```

**Comment by adamlarsonlee** [comment]
My guess is that it has something to do with UTC conversion? The code has a different logic path depending on if your using Windows or Linux.

**Comment by gagan-bansal** [comment]
I am using Linux.
@adam-larson-lee  Thanks for your support. 
Right now I don't require it. I was trying to use it for many test cases related to time.
